INSERT INTO interest (description,category_id,language_code) VALUES ('antiques', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('astrology', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('bars / pubs / nightclubs', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('board / card games', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('cars / mechanics', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('collecting', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('computers / internet', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('cooking / food and wine', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('dancing', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('dinner Parties', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('family', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('gardening / landscaping', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('investing / finance', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('library', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('motorcycles', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('museums / galleries', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('music (playing)', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('pets', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('photography', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('reading', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('shopping', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('tv: educational / news', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('theatre', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('video / online games', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('watching sports', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('writing', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('art / painting', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('ballet', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('beach / parks', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('camping / nature', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('casino / gambling', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('comedy clubs', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('concerts / live music', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('crafts', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('dining out', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('education', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('fashion events', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('home improvement', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('karaoke / sing-along', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('meditation', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('movies / cinema', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('music (listening)', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('news / politics', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('philosophy / spirituality', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('poetry', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('science and technology', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('social causes / activism', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('tv: entertainment', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('traveling', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('volunteering', 2, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('wine tasting', 2, 'en');

INSERT INTO interest (description,category_id,language_code) VALUES ('american', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('cajun / southern', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('caribbean / cuban', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('continental', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('eastern european', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('french', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('greek', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('italian', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('jewish / kosher', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('mediterranean', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('middle eastern', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('soul food', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('southwestern', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('vegan', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('vietnamese', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('barbecue', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('california-fusion', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('chinese / dim sum', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('deli', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('fast food / pizza', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('german', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('indian', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('japanese / sushi', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('korean', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('mexican', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('seafood', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('south american', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('thai', 4, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('vegetarian / organic', 4, 'en');

INSERT INTO interest (description,category_id,language_code) VALUES ('alternative', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('country / folk', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('jazz / blues', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('new age', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('rnb / hip hop', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('reggae', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('rock', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('world', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('classical / opera', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('dance / techno', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('metal', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('pop', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('rap', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('religious', 6, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('soft rock', 6, 'en');

INSERT INTO interest (description,category_id,language_code) VALUES ('aerobics', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('archery', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('aussie rules football', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('bmx / mountain biking', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('basketball', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('boating / sailing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('bowling', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('canoe / kayak', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('cricket', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('darts', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('extreme sports', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('fishing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('gym / weight training', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('hang gliding / paragliding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('hockey', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('hunting / shooting', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('in-line skating', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('jogging / running', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('martial arts', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('mountain / rock climbing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('pool / billards', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('rugby', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('skateboarding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('snowmobiling', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('squash / racquetball', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('swimming', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('tennis / badminton', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('walking', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('wrestling', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('american football', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('athletics', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('auto Racing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('baseball / Softball', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('biking', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('bodybuilding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('boxing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('canyoning / caving', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('cycling', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('diving', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('figure skating', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('golf', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('gymnastics', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('hiking', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('horse riding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('ice skating / ice hockey', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('jet / water skiing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('lacrosse', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('motor sports', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('netball', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('polo', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('rowing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('scuba diving / snorkeling', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('skiing / Snowboarding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('soccer', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('surfing', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('table tennis', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('volleyball', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('windsurfing / kite boarding', 8, 'en');
INSERT INTO interest (description,category_id,language_code) VALUES ('yoga / pilates', 8, 'en');

INSERT INTO interest (description,category_id,language_code) VALUES ('antikk', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('astrologi', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('bar / pub / nattkluber', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kortspill', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('biler / mekking', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('samling', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('datamaskiner / internett', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('matlaging / mat og vin', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('dansing', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('middagsselskap', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('familie', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('hagearbeid', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('investering / finans', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('bibliotek', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('motorsykkler', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('museum / gallerier', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('musikk (spille)', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kjeledyr', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fotografering', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('lesing', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('shopping', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('tv: utdanning / nyheter', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('theater', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('video / online spill', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('tv: sport', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('skriving', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kunst / maling', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('ballet', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('strand / park', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('camping / natur', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('casino / gambling', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('standup shows', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('konserter / live musikk', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('crafts', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('spise ute', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('utdanning', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('mote', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('hjemmeinredning', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('karaoke', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('meditasjon', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('filmer / kino', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('musikk (lytte)', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('nyheter / politikk', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('filosofi / spirituell', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('poesi', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vitenskap og teknologi', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('aktivisme', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('tv: underholdning', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('reising', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('frivillighetsarbeid', 2, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vinsmaking', 2, 'no');

INSERT INTO interest (description,category_id,language_code) VALUES ('amerikansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('cajun / sørlig', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('karibisk / cubansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kontinental', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('øst europeisk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fransk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('gresk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('italiensk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('jødisk / kosher', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('middelhavs', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('midtøsten', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('renselsesmat', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('sørvestlig amerikansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vegan', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vietnamesisk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('barbecue', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('california-fusion', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kinesisk / dim sum', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('deli', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fast food / pizza', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('tysk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('indisk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('japansk / sushi', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('koreansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('meksikansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('sjømat', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('sør amerikansk', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('thai', 4, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vegetar / organisk', 4, 'no');

INSERT INTO interest (description,category_id,language_code) VALUES ('alternativ', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('country / folk', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('jazz / blues', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('new age', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('rnb / hip hop', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('reggae', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('rock', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('world', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('klassisk / opera', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('dance / techno', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('metal', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('pop', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('rap', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('religiøs', 6, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('soft rock', 6, 'no');

INSERT INTO interest (description,category_id,language_code) VALUES ('aerobikk', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('pil og bue', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('aussie rules football', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('bmx / offroad', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('basketball', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('båt / seiling', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('bowling', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kano / kajak', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('cricket', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('dart', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('ekstrem sport', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fisking', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('gym / vekttrening', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('hanggliding / paragliding', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('hockey', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('jakt / skyting', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('in-line skøyter', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('jogging / springing', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('martial arts', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fjell klatring', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('pool / billard', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('rugby', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('skateboarding', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('snøscooter', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('squash / racquetball', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('svømming', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('tennis / badminton', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('spasering', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('wrestling', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('amerikansk football', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('friidrett', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('banesport', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('baseball / softball', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('sykling', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('kroppsbygging', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('boksing', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('dykking', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('golf', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('gymnastikk', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('haiking', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('riding', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('is skøyte / is hockey', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('jet / vannski', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('motorsport', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('polo', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('roing', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('snorkling', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('skikjøring / snowboarding', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('fotball', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('surfing', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('bord tennis', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('volleyball', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('vindsurfing / kite boarding', 8, 'no');
INSERT INTO interest (description,category_id,language_code) VALUES ('yoga / pilates', 8, 'no');



